void setup() 
{
  // put your setup code here, to run once:
  pinMode (5,OUTPUT);
  pinMode (6,OUTPUT);
  pinMode (7,OUTPUT);
  pinMode (8,OUTPUT);
}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite (5,LOW);
  digitalWrite (6,LOW);
  digitalWrite (7,LOW);
  digitalWrite (8,LOW);
  delay (1000);
  digitalWrite (5,LOW);
  digitalWrite (6,LOW);
  digitalWrite (7,LOW);
  digitalWrite (8,HIGH);
  delay (1000);
  digitalWrite (5,LOW);
  digitalWrite (6,LOW);
  digitalWrite (7,HIGH);
  digitalWrite (8,LOW);
  delay (1000);
  digitalWrite (5,LOW);
  digitalWrite (6,LOW);
  digitalWrite (7,HIGH);
  digitalWrite (8,HIGH);
  delay (1000);
  digitalWrite (5,LOW);
  digitalWrite (6,HIGH);
  digitalWrite (7,LOW);
  digitalWrite (8,LOW);
  delay (1000);
  digitalWrite (5,LOW);
  digitalWrite (6,HIGH);
  digitalWrite (7,LOW);
  digitalWrite (8,HIGH);
  delay (1000);
  digitalWrite (5,LOW);
  digitalWrite (6,HIGH);
  digitalWrite (7,HIGH);
  digitalWrite (8,LOW);
  delay (1000);
  digitalWrite (5,LOW);
  digitalWrite (6,HIGH);
  digitalWrite (7,HIGH);
  digitalWrite (8,HIGH);
  delay (1000);
  digitalWrite (5,HIGH);
  digitalWrite (6,LOW);
  digitalWrite (7,LOW);
  digitalWrite (8,LOW);
  delay (1000);
  digitalWrite (5,HIGH);
  digitalWrite (6,LOW);
  digitalWrite (7,LOW);
  digitalWrite (8,HIGH);
  delay (1000);
  digitalWrite (5,HIGH);
  digitalWrite (6,LOW);
  digitalWrite (7,HIGH);
  digitalWrite (8,LOW);
  delay (1000);
  digitalWrite (5,HIGH);
  digitalWrite (6,LOW);
  digitalWrite (7,HIGH);
  digitalWrite (8,HIGH);
  delay (1000);
  digitalWrite (5,HIGH);
  digitalWrite (6,HIGH);
  digitalWrite (7,LOW);
  digitalWrite (8,LOW);
  delay (1000);
  digitalWrite (5,HIGH);
  digitalWrite (6,HIGH);
  digitalWrite (7,LOW);
  digitalWrite (8,HIGH);
  delay (1000);
  digitalWrite (5,HIGH);
  digitalWrite (6,HIGH);
  digitalWrite (7,HIGH);
  digitalWrite (8,LOW);
  delay (1000);
  digitalWrite (5,HIGH);
  digitalWrite (6,HIGH);
  digitalWrite (7,HIGH);
  digitalWrite (8,HIGH);
  delay (1000);
  }
  
